## Numpy Başlangıç

In [1]:
import numpy as np

### Numpy Array

In [2]:
benimListem = [20,30,40]

In [3]:
type(benimListem)

list

In [4]:
np.array(benimListem)

array([20, 30, 40])

In [5]:
matrixListesi = [[10,20,30],[20,30,40],[30,40,50]]

In [6]:
matrixListesi[1][0]

20

In [7]:
np.array(matrixListesi)

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50]])

### Numpy Mothodları

#### Arange:

In [8]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### zeros:          ones:

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [14]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### linspace:

In [17]:
np.linspace(0,20,6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [19]:
np.linspace(0,10,15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

#### eye:

In [20]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

#### random:

In [22]:
np.random.randn(4)

array([ 0.78553181, -0.09811157, -2.47181865, -1.74953417])

In [23]:
np.random.randn(3,3)

array([[-0.10649351,  1.29842086, -0.37600238],
       [ 0.52475178, -1.13027755, -0.50237548],
       [-0.45033327, -1.40199174, -0.70692141]])

In [24]:
np.random.randint(1,10)

2

-1 döndürür 10 döndürmez.

In [25]:
np.random.randint(1,10,5)

array([3, 9, 7, 2, 7])

In [26]:
benimNumpyDizim = np.arange(30)

In [27]:
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [32]:
benimRandomDizim = np.random.randint(0,100,20)

In [33]:
benimRandomDizim

array([85, 26, 44, 76, 32, 29, 70, 85, 48, 80, 70, 38, 37, 24, 83, 37, 53,
       56, 61, 77])

### Numpy Dizi Methodları

In [34]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [35]:
benimNumpyDizim.max()

29

In [36]:
benimRandomDizim.max()

85

In [37]:
benimRandomDizim.min()

24

In [38]:
benimRandomDizim.argmax()

0

In [39]:
benimRandomDizim.argmin()

13

In [40]:
benimNumpyDizim.shape

(30,)

In [41]:
reshapeDizim = benimNumpyDizim.reshape(5,6)

In [42]:
reshapeDizim.shape

(5, 6)

### Numpy İndexler:

In [43]:
import numpy as np

In [44]:
benimDizim = np.arange(0,15)

In [45]:
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
benimDizim[5]

5

In [51]:
benimDizim[3:8]

array([3, 4, 5, 6, 7])

In [52]:
benimDizim[3:8] = -5

In [53]:
benimDizim

array([ 0,  1,  2, -5, -5, -5, -5, -5,  8,  9, 10, 11, 12, 13, 14])

In [54]:
baskaDizi = np.arange(0,24)

In [55]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
baskaDizi[4:9]

array([4, 5, 6, 7, 8])

In [58]:
slicingDizi = baskaDizi[4:9]

In [59]:
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [60]:
slicingDizi = 700

In [61]:
type(slicingDizi)

int

In [62]:
slicingDizi = baskaDizi[4:9]

In [63]:
slicingDizi

array([4, 5, 6, 7, 8])

In [64]:
slicingDizi[:] = 700

In [65]:
slicingDizi

array([700, 700, 700, 700, 700])

In [66]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [67]:
ornekDizi = np.arange(0,24)

In [68]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
ornekDiziKopyasi = ornekDizi.copy()

In [70]:
ornekDiziKopyasi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [71]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [72]:
ornekDiziKopyasiSlicing = ornekDiziKopyasi[3:6]

In [75]:
ornekDiziKopyasiSlicing[:] = 800

In [76]:
ornekDiziKopyasiSlicing

array([800, 800, 800])

In [77]:
ornekDiziKopyasi

array([  0,   1,   2, 800, 800, 800,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])

In [78]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

### Matrix İndexler:

In [79]:
benimListem = [[10,20,30],[20,30,40],[40,50,60]]

In [80]:
benimMatrixDizim = np.array(benimListem)

In [81]:
benimMatrixDizim

array([[10, 20, 30],
       [20, 30, 40],
       [40, 50, 60]])

In [82]:
benimMatrixDizim[0]

array([10, 20, 30])

In [83]:
benimMatrixDizim[1][2]

40

In [84]:
benimMatrixDizim[1,2]

40

In [85]:
benimMatrixDizim[1:,2]

array([40, 60])

In [86]:
benimMatrixDizim[0:,2]

array([30, 40, 60])

In [89]:
benimMatrixDizim[2:,2:]

array([[60]])

In [90]:
yeniListe = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]]

In [91]:
yeniMatrix = np.array(yeniListe)

In [92]:
yeniListe

[[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14],
 [15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24]]

In [93]:
yeniMatrix[[4,2,0]]

array([[20, 21, 22, 23, 24],
       [10, 11, 12, 13, 14],
       [ 0,  1,  2,  3,  4]])

### Numpy Operasyonlar:

In [94]:
yeniBirDizi = np.arange(5,25)

In [95]:
yeniBirDizi

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24])

In [96]:
yeniBirDizi = np.random.randint(1,100,20)

In [97]:
yeniBirDizi

array([ 5, 61, 74, 94, 42, 95, 34, 37, 17, 17, 21, 16, 36, 79, 16, 97, 42,
       93,  4, 34])

In [98]:
yeniBirDizi > 24

array([False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True])

In [99]:
yeniBirDizi

array([ 5, 61, 74, 94, 42, 95, 34, 37, 17, 17, 21, 16, 36, 79, 16, 97, 42,
       93,  4, 34])

In [100]:
sonucDizisi = yeniBirDizi > 24

In [101]:
yeniBirDizi

array([ 5, 61, 74, 94, 42, 95, 34, 37, 17, 17, 21, 16, 36, 79, 16, 97, 42,
       93,  4, 34])

In [103]:
yeniBirDizi[sonucDizisi]

array([61, 74, 94, 42, 95, 34, 37, 36, 79, 97, 42, 93, 34])

In [104]:
yeniBirDizi

array([ 5, 61, 74, 94, 42, 95, 34, 37, 17, 17, 21, 16, 36, 79, 16, 97, 42,
       93,  4, 34])

In [105]:
yeniBirDizi[yeniBirDizi > 24]

array([61, 74, 94, 42, 95, 34, 37, 36, 79, 97, 42, 93, 34])

In [106]:
sonDizi = np.arange(0,24)

In [107]:
sonDizi + sonDizi

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [108]:
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [109]:
sonDizi * sonDizi

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [110]:
sonDizi - sonDizi

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [111]:
sonDizi / sonDizi

<ipython-input-111-20a5ae775714>:1: RuntimeWarning: invalid value encountered in true_divide
  sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

-Uyarı verebilir. Sıfır ile bölme olduğu için.

In [112]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [113]:
np.max(sonDizi)

23

In [114]:
np.min(sonDizi)

0